controller_list:
  - name: fake_Arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_hand_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_6
      - joint_7
initial:  # Define initial robot poses per group
  - group: Arm_group
    pose: arm_straight
  - group: hand_group
    pose: hand_closed